# Generated by Django 5.2.1 on 2025-06-18 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
